# Версия синтаксиса docker-compose
version: '3.8'

# Определяем наши сервисы (контейнеры)
services:

  # Сервис для нашего Flask-приложения
  web:
    build: .
    container_name: education-platform-app
    restart: always
    environment:
      # ВАЖНО: Перенесите сюда ваши секреты. Не храните их в коде!
      - FLASK_SECRET_KEY=ВАШ_СУПЕР_СЕКРЕТНЫЙ_КЛЮЧ
      - GIGACHAT_CREDENTIALS=ВАШИ_УЧЕТНЫЕ_ДАННЫЕ_GIGACHAT
      - FLASK_APP=app.py
    volumes:
      # Синхронизируем папку instance, чтобы база данных сохранялась на хосте
      - instance_data:/app/instance
    expose:
      # Открываем порт 5000 для Nginx (внутри Docker-сети)
      - "5000"

  # Сервис для Nginx
  nginx:
    image: nginx:1.21-alpine
    container_name: education-platform-nginx
    restart: always
    ports:
      # Пробрасываем порты 80 и 443 с хоста в контейнер
      - "80:80"
      - "443:443"
    volumes:
      # Подключаем конфигурацию Nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # Подключаем статические файлы (в режиме "только чтение")
      - ./education_platform/education_platform/static:/app/static:ro
      # Подключаем папку с SSL-сертификатами
      - ssl_certs:/etc/nginx/ssl
    depends_on:
      - web

volumes:
  ssl_certs:
  instance_data:
